name: josh-Testing internal action in this org

on: workflow_dispatch

jobs:
  my-job:
    name: Consume internal action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: Internal-Actions/josh-action-3@v2
        with:
          milliseconds: 1000
          
      - uses: Internal-Actions/josh-internal-action-2@v2
        with:
          milliseconds: 1000
